---
- hosts: all
  become: true

  tasks:
   - name: Install Apache2
     apt:
       state: present
       update_cache: yes
       name: apache2
   
   - name: Delete /etc/apache2/sites-enabled/000-default.conf
     file:
       state: absent
       path: /etc/apache2/sites-enabled/000-default.conf

   - name: Install MySQL
     apt:
       state: present
       update_cache: yes
       name:
       - mysql-server
       - python-mysqldb

   - name: Install PHP
     apt:
       state: present
       update_cache: yes
       name: 
       - php
       - php-mysql
       - libapache2-mod-php

   - name: Install wordpress
     apt:
       state: present
       update_cache: yes
       name: wordpress

   - name: Create /etc/apache2/sites-available/wordpress.conf
     template:
       src: templates/wordpress/wordpress.conf
       dest: /etc/apache2/sites-available/wordpress.conf

   - name: Execute a2ensite wordpress
     command: a2ensite wordpress

   - name: Restart apache2 service
     systemd:
       name: apache2
       state: reloaded

   - name: Create /etc/wordpress/config-192.168.33.30.php
     template:
       src: templates/wordpress/config-192.168.33.30.php
       dest: /etc/wordpress/config-192.168.33.30.php

   - name: Create WordPress MySQL database
     mysql_db:
       name: wordpress
       state: present

   - name: Create WordPress MySQL user
     mysql_user:
       name: wordpress
       host: localhost
       password: wordpress
       priv: wordpress.*:ALL

   - name: Does the database exist?
     command: mysql -u root wordpress -e "SELECT ID FROM wordpress.wp_users LIMIT 1;"
     register: db_exist
     ignore_errors: true
     changed_when: false

   - name: Copy WordPress DB
     template:
       src: files/wp-database.sql
       dest: /tmp/wp-database.sql
     when: db_exist.rc > 0

   - name: Import WordPress DB
     mysql_db:
       target: /tmp/wp-database.sql
       state: import
       name: wordpress
     when: db_exist.rc > 0
